FROM ghcr.io/osgeo/gdal:ubuntu-small-latest

WORKDIR /app

COPY ./scripts ./scripts
COPY ./backend ./backend
COPY ./public ./public
COPY .netrc /root/.netrc
COPY ./scheduler ./

RUN chmod 600 /root/.netrc
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install --break-system-packages -r ./scripts/lib/requirements.txt
RUN apt-get install -y wget

RUN chmod +x ./scheduler

#First run to check if dependencies are fine!
RUN python3 ./scripts/tshoRolpa.py

CMD ["./scheduler"]

#Build and Run instructions
#docker build -t cron-cont .
#docker run -d --restart unless-stopped -v $(pwd)/scripts/:/app/scripts/ -v $(pwd)/public/:/app/public/ cron-cont
